TAH.ShopTypeToPrice = {
    ["1Pistol"] = {
        ["0Exotic"] = 7,
        ["1Elite"] = 7,
        ["2Operator"] = 5,
        ["3Security"] = 3,
        ["4Consumer"] = 2,
        ["5Value"] = 1,
    },
    ["2Magnum Pistol"] = {
        ["0Exotic"] = 9,
        ["1Elite"] = 9,
        ["2Operator"] = 7,
        ["3Security"] = 5,
        ["4Consumer"] = 4,
        ["5Value"] = 2,
    },
    ["3Machine Pistol"] = {
        ["0Exotic"] = 10,
        ["1Elite"] = 10,
        ["2Operator"] = 8,
        ["3Security"] = 6,
        ["4Consumer"] = 5,
        ["5Value"] = 4,
    },
    ["3Akimbo"] = {
        ["0Exotic"] = 8,
        ["1Elite"] = 8,
        ["2Operator"] = 6,
        ["3Security"] = 4,
        ["4Consumer"] = 3,
        ["5Value"] = 2,
    },
    ["3Submachine Gun"] = {
        ["0Exotic"] = 13,
        ["1Elite"] = 13,
        ["2Operator"] = 11,
        ["3Security"] = 9,
        ["4Consumer"] = 7,
        ["5Value"] = 5,
    },
    ["4Assault Rifle"] = {
        ["0Exotic"] = 15,
        ["1Elite"] = 15,
        ["2Operator"] = 13,
        ["3Security"] = 11,
        ["4Consumer"] = 9,
        ["5Value"] = 7,
    },
    ["5Battle Rifle"] = {
        ["0Exotic"] = 15,
        ["1Elite"] = 15,
        ["2Operator"] = 13,
        ["3Security"] = 11,
        ["4Consumer"] = 9,
        ["5Value"] = 7,
    },
    ["5Machine Gun"] = {
        ["0Exotic"] = 16,
        ["1Elite"] = 16,
        ["2Operator"] = 14,
        ["3Security"] = 12,
        ["4Consumer"] = 10,
        ["5Value"] = 8,
    },
    ["5Shotgun"] = {
        ["0Exotic"] = 13,
        ["1Elite"] = 13,
        ["2Operator"] = 11,
        ["3Security"] = 9,
        ["4Consumer"] = 7,
        ["5Value"] = 5,
    },
    ["5Sporter"] = {
        ["0Exotic"] = 11,
        ["1Elite"] = 11,
        ["2Operator"] = 9,
        ["3Security"] = 7,
        ["4Consumer"] = 5,
        ["5Value"] = 4,
    },
    ["6Marksman Rifle"] = {
        ["0Exotic"] = 12,
        ["1Elite"] = 12,
        ["2Operator"] = 10,
        ["3Security"] = 7,
        ["4Consumer"] = 5,
        ["5Value"] = 2,
    },
    ["7Sniper Rifle"] = {
        ["0Exotic"] = 9,
        ["1Elite"] = 9,
        ["2Operator"] = 6,
        ["3Security"] = 4,
        ["4Consumer"] = 2,
        ["5Value"] = 2,
    },
}